"""add details json column to projects

Revision ID: 75d066960334
Revises: b7c8d9e0f1a2
Create Date: 2026-08-08 15:12:35.769841

"""
# Dùng cú pháp `X | Y` và collections.abc thay cho typing.Union/Sequence để file
# sinh ra đã hợp lệ với ruff (UP007/UP035/I001), khỏi phải sửa tay mỗi revision.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '75d066960334'
# Re-parented onto b7c8d9e0f1a2 when feature/Linh merged into develop: both
# branches wrote a revision whose down_revision was the baseline, which left
# Alembic with two heads and `upgrade head` refusing to run. This migration only
# adds projects.details, independent of the chat_sessions/messages columns on the
# other branch, so ordering it last is safe.
down_revision: str | Sequence[str] | None = 'b7c8d9e0f1a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'details')
    # ### end Alembic commands ###
