"""add details json column to projects

Revision ID: 75d066960334
Revises: df3813c946cc
Create Date: 2026-08-08 15:12:35.769841

"""
# Dùng cú pháp `X | Y` và collections.abc thay cho typing.Union/Sequence để file
# sinh ra đã hợp lệ với ruff (UP007/UP035/I001), khỏi phải sửa tay mỗi revision.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '75d066960334'
down_revision: str | Sequence[str] | None = 'df3813c946cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'details')
    # ### end Alembic commands ###
